version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: terminal


  cloud-terminal:
    depends_on:
      - db
    image: 0809/cloud-terminal:v1.6
    ports:
      - "2021:2021"
    restart: always
    environment:
      cloud-terminal_DB_HOST: db:3306
volumes:
  db_data: {}
  cloud-terminal_data: {}