#version: "3.9"
#
#services:
#  db:
#    image: mysql:8.0
#    volumes:
#      - db_data:/var/lib/mysql
#    command:
#      - --default_authentication_plugin=mysql_native_password
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE: terminal
#
#
#  cloud-terminal:
#    depends_on:
#      - db
#    image: 0809/cloud-terminal:v1.6
#    ports:
#      - "2023:2023"
#    restart: unless-stopped
#    environment:
#      cloud-terminal_DB_HOST: db:3306
#volumes:
#  db_data: {}
#  cloud-terminal_data: {}

version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: terminal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  cloud-terminal:
    depends_on:
      db:
        condition: service_healthy
    image: 0809/cloud-terminal:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: terminal
      DB_TYPE: mysql

  frontend:
    image: 0809/terminal-dashboard:latest
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    environment:
      API_URL: https://cloud-terminal

volumes:
  db_data: {}
  cloud-terminal_data: {}
