// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/cloud-terminal/pkg/database/ent/accesssecurity"
	"github.com/willie-lin/cloud-terminal/pkg/database/ent/asset"
	"github.com/willie-lin/cloud-terminal/pkg/database/ent/predicate"
)

// AccessSecurityQuery is the builder for querying AccessSecurity entities.
type AccessSecurityQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AccessSecurity
	// eager-loading edges.
	withAssets *AssetQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessSecurityQuery builder.
func (asq *AccessSecurityQuery) Where(ps ...predicate.AccessSecurity) *AccessSecurityQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit adds a limit step to the query.
func (asq *AccessSecurityQuery) Limit(limit int) *AccessSecurityQuery {
	asq.limit = &limit
	return asq
}

// Offset adds an offset step to the query.
func (asq *AccessSecurityQuery) Offset(offset int) *AccessSecurityQuery {
	asq.offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *AccessSecurityQuery) Unique(unique bool) *AccessSecurityQuery {
	asq.unique = &unique
	return asq
}

// Order adds an order step to the query.
func (asq *AccessSecurityQuery) Order(o ...OrderFunc) *AccessSecurityQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// QueryAssets chains the current query on the "assets" edge.
func (asq *AccessSecurityQuery) QueryAssets() *AssetQuery {
	query := &AssetQuery{config: asq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := asq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := asq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesssecurity.Table, accesssecurity.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesssecurity.AssetsTable, accesssecurity.AssetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(asq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessSecurity entity from the query.
// Returns a *NotFoundError when no AccessSecurity was found.
func (asq *AccessSecurityQuery) First(ctx context.Context) (*AccessSecurity, error) {
	nodes, err := asq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accesssecurity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *AccessSecurityQuery) FirstX(ctx context.Context) *AccessSecurity {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessSecurity ID from the query.
// Returns a *NotFoundError when no AccessSecurity ID was found.
func (asq *AccessSecurityQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = asq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accesssecurity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *AccessSecurityQuery) FirstIDX(ctx context.Context) string {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessSecurity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AccessSecurity entity is not found.
// Returns a *NotFoundError when no AccessSecurity entities are found.
func (asq *AccessSecurityQuery) Only(ctx context.Context) (*AccessSecurity, error) {
	nodes, err := asq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accesssecurity.Label}
	default:
		return nil, &NotSingularError{accesssecurity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *AccessSecurityQuery) OnlyX(ctx context.Context) *AccessSecurity {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessSecurity ID in the query.
// Returns a *NotSingularError when exactly one AccessSecurity ID is not found.
// Returns a *NotFoundError when no entities are found.
func (asq *AccessSecurityQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = asq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = &NotSingularError{accesssecurity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *AccessSecurityQuery) OnlyIDX(ctx context.Context) string {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessSecurities.
func (asq *AccessSecurityQuery) All(ctx context.Context) ([]*AccessSecurity, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return asq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (asq *AccessSecurityQuery) AllX(ctx context.Context) []*AccessSecurity {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessSecurity IDs.
func (asq *AccessSecurityQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := asq.Select(accesssecurity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *AccessSecurityQuery) IDsX(ctx context.Context) []string {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *AccessSecurityQuery) Count(ctx context.Context) (int, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return asq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (asq *AccessSecurityQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *AccessSecurityQuery) Exist(ctx context.Context) (bool, error) {
	if err := asq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return asq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *AccessSecurityQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessSecurityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *AccessSecurityQuery) Clone() *AccessSecurityQuery {
	if asq == nil {
		return nil
	}
	return &AccessSecurityQuery{
		config:     asq.config,
		limit:      asq.limit,
		offset:     asq.offset,
		order:      append([]OrderFunc{}, asq.order...),
		predicates: append([]predicate.AccessSecurity{}, asq.predicates...),
		withAssets: asq.withAssets.Clone(),
		// clone intermediate query.
		sql:  asq.sql.Clone(),
		path: asq.path,
	}
}

// WithAssets tells the query-builder to eager-load the nodes that are connected to
// the "assets" edge. The optional arguments are used to configure the query builder of the edge.
func (asq *AccessSecurityQuery) WithAssets(opts ...func(*AssetQuery)) *AccessSecurityQuery {
	query := &AssetQuery{config: asq.config}
	for _, opt := range opts {
		opt(query)
	}
	asq.withAssets = query
	return asq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Rule string `json:"rule,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessSecurity.Query().
//		GroupBy(accesssecurity.FieldRule).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (asq *AccessSecurityQuery) GroupBy(field string, fields ...string) *AccessSecurityGroupBy {
	group := &AccessSecurityGroupBy{config: asq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := asq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return asq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Rule string `json:"rule,omitempty"`
//	}
//
//	client.AccessSecurity.Query().
//		Select(accesssecurity.FieldRule).
//		Scan(ctx, &v)
//
func (asq *AccessSecurityQuery) Select(field string, fields ...string) *AccessSecuritySelect {
	asq.fields = append([]string{field}, fields...)
	return &AccessSecuritySelect{AccessSecurityQuery: asq}
}

func (asq *AccessSecurityQuery) prepareQuery(ctx context.Context) error {
	for _, f := range asq.fields {
		if !accesssecurity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *AccessSecurityQuery) sqlAll(ctx context.Context) ([]*AccessSecurity, error) {
	var (
		nodes       = []*AccessSecurity{}
		_spec       = asq.querySpec()
		loadedTypes = [1]bool{
			asq.withAssets != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AccessSecurity{config: asq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := asq.withAssets; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[string]*AccessSecurity)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Assets = []*Asset{}
		}
		query.withFKs = true
		query.Where(predicate.Asset(func(s *sql.Selector) {
			s.Where(sql.InValues(accesssecurity.AssetsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.access_security_assets
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "access_security_assets" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "access_security_assets" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Assets = append(node.Edges.Assets, n)
		}
	}

	return nodes, nil
}

func (asq *AccessSecurityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *AccessSecurityQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := asq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (asq *AccessSecurityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accesssecurity.Table,
			Columns: accesssecurity.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: accesssecurity.FieldID,
			},
		},
		From:   asq.sql,
		Unique: true,
	}
	if unique := asq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := asq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesssecurity.FieldID)
		for i := range fields {
			if fields[i] != accesssecurity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *AccessSecurityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(accesssecurity.Table)
	selector := builder.Select(t1.Columns(accesssecurity.Columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(accesssecurity.Columns...)...)
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessSecurityGroupBy is the group-by builder for AccessSecurity entities.
type AccessSecurityGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *AccessSecurityGroupBy) Aggregate(fns ...AggregateFunc) *AccessSecurityGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the group-by query and scans the result into the given value.
func (asgb *AccessSecurityGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := asgb.path(ctx)
	if err != nil {
		return err
	}
	asgb.sql = query
	return asgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := asgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(asgb.fields) > 1 {
		return nil, errors.New("ent: AccessSecurityGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := asgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) StringsX(ctx context.Context) []string {
	v, err := asgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = asgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecurityGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) StringX(ctx context.Context) string {
	v, err := asgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(asgb.fields) > 1 {
		return nil, errors.New("ent: AccessSecurityGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := asgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) IntsX(ctx context.Context) []int {
	v, err := asgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = asgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecurityGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) IntX(ctx context.Context) int {
	v, err := asgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(asgb.fields) > 1 {
		return nil, errors.New("ent: AccessSecurityGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := asgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := asgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = asgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecurityGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) Float64X(ctx context.Context) float64 {
	v, err := asgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(asgb.fields) > 1 {
		return nil, errors.New("ent: AccessSecurityGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := asgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := asgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (asgb *AccessSecurityGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = asgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecurityGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (asgb *AccessSecurityGroupBy) BoolX(ctx context.Context) bool {
	v, err := asgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (asgb *AccessSecurityGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range asgb.fields {
		if !accesssecurity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := asgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (asgb *AccessSecurityGroupBy) sqlQuery() *sql.Selector {
	selector := asgb.sql
	columns := make([]string, 0, len(asgb.fields)+len(asgb.fns))
	columns = append(columns, asgb.fields...)
	for _, fn := range asgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(asgb.fields...)
}

// AccessSecuritySelect is the builder for selecting fields of AccessSecurity entities.
type AccessSecuritySelect struct {
	*AccessSecurityQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ass *AccessSecuritySelect) Scan(ctx context.Context, v interface{}) error {
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	ass.sql = ass.AccessSecurityQuery.sqlQuery(ctx)
	return ass.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ass *AccessSecuritySelect) ScanX(ctx context.Context, v interface{}) {
	if err := ass.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Strings(ctx context.Context) ([]string, error) {
	if len(ass.fields) > 1 {
		return nil, errors.New("ent: AccessSecuritySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ass.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ass *AccessSecuritySelect) StringsX(ctx context.Context) []string {
	v, err := ass.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ass.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecuritySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ass *AccessSecuritySelect) StringX(ctx context.Context) string {
	v, err := ass.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Ints(ctx context.Context) ([]int, error) {
	if len(ass.fields) > 1 {
		return nil, errors.New("ent: AccessSecuritySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ass.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ass *AccessSecuritySelect) IntsX(ctx context.Context) []int {
	v, err := ass.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ass.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecuritySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ass *AccessSecuritySelect) IntX(ctx context.Context) int {
	v, err := ass.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ass.fields) > 1 {
		return nil, errors.New("ent: AccessSecuritySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ass.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ass *AccessSecuritySelect) Float64sX(ctx context.Context) []float64 {
	v, err := ass.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ass.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecuritySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ass *AccessSecuritySelect) Float64X(ctx context.Context) float64 {
	v, err := ass.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ass.fields) > 1 {
		return nil, errors.New("ent: AccessSecuritySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ass.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ass *AccessSecuritySelect) BoolsX(ctx context.Context) []bool {
	v, err := ass.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ass *AccessSecuritySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ass.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{accesssecurity.Label}
	default:
		err = fmt.Errorf("ent: AccessSecuritySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ass *AccessSecuritySelect) BoolX(ctx context.Context) bool {
	v, err := ass.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ass *AccessSecuritySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ass.sqlQuery().Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ass *AccessSecuritySelect) sqlQuery() sql.Querier {
	selector := ass.sql
	selector.Select(selector.Columns(ass.fields...)...)
	return selector
}
