// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/willie-lin/cloud-terminal/app/database/ent/auditlog"
	"github.com/willie-lin/cloud-terminal/app/database/ent/predicate"
	"github.com/willie-lin/cloud-terminal/app/database/ent/tenant"
	"github.com/willie-lin/cloud-terminal/app/database/ent/user"
)

// AuditLogQuery is the builder for querying AuditLog entities.
type AuditLogQuery struct {
	config
	ctx        *QueryContext
	order      []auditlog.OrderOption
	inters     []Interceptor
	predicates []predicate.AuditLog
	withUser   *UserQuery
	withTenant *TenantQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuditLogQuery builder.
func (alq *AuditLogQuery) Where(ps ...predicate.AuditLog) *AuditLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *AuditLogQuery) Limit(limit int) *AuditLogQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *AuditLogQuery) Offset(offset int) *AuditLogQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *AuditLogQuery) Unique(unique bool) *AuditLogQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *AuditLogQuery) Order(o ...auditlog.OrderOption) *AuditLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// QueryUser chains the current query on the "user" edge.
func (alq *AuditLogQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(auditlog.Table, auditlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, auditlog.UserTable, auditlog.UserPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenant chains the current query on the "tenant" edge.
func (alq *AuditLogQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(auditlog.Table, auditlog.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, auditlog.TenantTable, auditlog.TenantPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuditLog entity from the query.
// Returns a *NotFoundError when no AuditLog was found.
func (alq *AuditLogQuery) First(ctx context.Context) (*AuditLog, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{auditlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *AuditLogQuery) FirstX(ctx context.Context) *AuditLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuditLog ID from the query.
// Returns a *NotFoundError when no AuditLog ID was found.
func (alq *AuditLogQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{auditlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *AuditLogQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuditLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuditLog entity is found.
// Returns a *NotFoundError when no AuditLog entities are found.
func (alq *AuditLogQuery) Only(ctx context.Context) (*AuditLog, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{auditlog.Label}
	default:
		return nil, &NotSingularError{auditlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *AuditLogQuery) OnlyX(ctx context.Context) *AuditLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuditLog ID in the query.
// Returns a *NotSingularError when more than one AuditLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *AuditLogQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{auditlog.Label}
	default:
		err = &NotSingularError{auditlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *AuditLogQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuditLogs.
func (alq *AuditLogQuery) All(ctx context.Context) ([]*AuditLog, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryAll)
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuditLog, *AuditLogQuery]()
	return withInterceptors[[]*AuditLog](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *AuditLogQuery) AllX(ctx context.Context) []*AuditLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuditLog IDs.
func (alq *AuditLogQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryIDs)
	if err = alq.Select(auditlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *AuditLogQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *AuditLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryCount)
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*AuditLogQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *AuditLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *AuditLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryExist)
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *AuditLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuditLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *AuditLogQuery) Clone() *AuditLogQuery {
	if alq == nil {
		return nil
	}
	return &AuditLogQuery{
		config:     alq.config,
		ctx:        alq.ctx.Clone(),
		order:      append([]auditlog.OrderOption{}, alq.order...),
		inters:     append([]Interceptor{}, alq.inters...),
		predicates: append([]predicate.AuditLog{}, alq.predicates...),
		withUser:   alq.withUser.Clone(),
		withTenant: alq.withTenant.Clone(),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AuditLogQuery) WithUser(opts ...func(*UserQuery)) *AuditLogQuery {
	query := (&UserClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withUser = query
	return alq
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AuditLogQuery) WithTenant(opts ...func(*TenantQuery)) *AuditLogQuery {
	query := (&TenantClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withTenant = query
	return alq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuditLog.Query().
//		GroupBy(auditlog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (alq *AuditLogQuery) GroupBy(field string, fields ...string) *AuditLogGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuditLogGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = auditlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AuditLog.Query().
//		Select(auditlog.FieldCreatedAt).
//		Scan(ctx, &v)
func (alq *AuditLogQuery) Select(fields ...string) *AuditLogSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &AuditLogSelect{AuditLogQuery: alq}
	sbuild.label = auditlog.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuditLogSelect configured with the given aggregations.
func (alq *AuditLogQuery) Aggregate(fns ...AggregateFunc) *AuditLogSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *AuditLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !auditlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *AuditLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuditLog, error) {
	var (
		nodes       = []*AuditLog{}
		_spec       = alq.querySpec()
		loadedTypes = [2]bool{
			alq.withUser != nil,
			alq.withTenant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuditLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuditLog{config: alq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := alq.withUser; query != nil {
		if err := alq.loadUser(ctx, query, nodes,
			func(n *AuditLog) { n.Edges.User = []*User{} },
			func(n *AuditLog, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := alq.withTenant; query != nil {
		if err := alq.loadTenant(ctx, query, nodes,
			func(n *AuditLog) { n.Edges.Tenant = []*Tenant{} },
			func(n *AuditLog, e *Tenant) { n.Edges.Tenant = append(n.Edges.Tenant, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (alq *AuditLogQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*AuditLog, init func(*AuditLog), assign func(*AuditLog, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*AuditLog)
	nids := make(map[uuid.UUID]map[*AuditLog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(auditlog.UserTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(auditlog.UserPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(auditlog.UserPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(auditlog.UserPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*AuditLog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "user" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (alq *AuditLogQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*AuditLog, init func(*AuditLog), assign func(*AuditLog, *Tenant)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*AuditLog)
	nids := make(map[uuid.UUID]map[*AuditLog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(auditlog.TenantTable)
		s.Join(joinT).On(s.C(tenant.FieldID), joinT.C(auditlog.TenantPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(auditlog.TenantPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(auditlog.TenantPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*AuditLog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Tenant](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tenant" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (alq *AuditLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *AuditLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for i := range fields {
			if fields[i] != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *AuditLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(auditlog.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = auditlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuditLogGroupBy is the group-by builder for AuditLog entities.
type AuditLogGroupBy struct {
	selector
	build *AuditLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *AuditLogGroupBy) Aggregate(fns ...AggregateFunc) *AuditLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *AuditLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, ent.OpQueryGroupBy)
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuditLogQuery, *AuditLogGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *AuditLogGroupBy) sqlScan(ctx context.Context, root *AuditLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuditLogSelect is the builder for selecting fields of AuditLog entities.
type AuditLogSelect struct {
	*AuditLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *AuditLogSelect) Aggregate(fns ...AggregateFunc) *AuditLogSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *AuditLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, ent.OpQuerySelect)
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuditLogQuery, *AuditLogSelect](ctx, als.AuditLogQuery, als, als.inters, v)
}

func (als *AuditLogSelect) sqlScan(ctx context.Context, root *AuditLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
