// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/willie-lin/cloud-terminal/app/database/ent/auditlog"
	"github.com/willie-lin/cloud-terminal/app/database/ent/predicate"
	"github.com/willie-lin/cloud-terminal/app/database/ent/tenant"
	"github.com/willie-lin/cloud-terminal/app/database/ent/user"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (alu *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetUpdatedAt sets the "updated_at" field.
func (alu *AuditLogUpdate) SetUpdatedAt(t time.Time) *AuditLogUpdate {
	alu.mutation.SetUpdatedAt(t)
	return alu
}

// SetActorID sets the "actor_id" field.
func (alu *AuditLogUpdate) SetActorID(i int) *AuditLogUpdate {
	alu.mutation.ResetActorID()
	alu.mutation.SetActorID(i)
	return alu
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableActorID(i *int) *AuditLogUpdate {
	if i != nil {
		alu.SetActorID(*i)
	}
	return alu
}

// AddActorID adds i to the "actor_id" field.
func (alu *AuditLogUpdate) AddActorID(i int) *AuditLogUpdate {
	alu.mutation.AddActorID(i)
	return alu
}

// SetActorUsername sets the "actor_username" field.
func (alu *AuditLogUpdate) SetActorUsername(s string) *AuditLogUpdate {
	alu.mutation.SetActorUsername(s)
	return alu
}

// SetNillableActorUsername sets the "actor_username" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableActorUsername(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetActorUsername(*s)
	}
	return alu
}

// SetAction sets the "action" field.
func (alu *AuditLogUpdate) SetAction(s string) *AuditLogUpdate {
	alu.mutation.SetAction(s)
	return alu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableAction(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetAction(*s)
	}
	return alu
}

// SetResourceID sets the "resource_id" field.
func (alu *AuditLogUpdate) SetResourceID(i int) *AuditLogUpdate {
	alu.mutation.ResetResourceID()
	alu.mutation.SetResourceID(i)
	return alu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableResourceID(i *int) *AuditLogUpdate {
	if i != nil {
		alu.SetResourceID(*i)
	}
	return alu
}

// AddResourceID adds i to the "resource_id" field.
func (alu *AuditLogUpdate) AddResourceID(i int) *AuditLogUpdate {
	alu.mutation.AddResourceID(i)
	return alu
}

// ClearResourceID clears the value of the "resource_id" field.
func (alu *AuditLogUpdate) ClearResourceID() *AuditLogUpdate {
	alu.mutation.ClearResourceID()
	return alu
}

// SetResourceType sets the "resource_type" field.
func (alu *AuditLogUpdate) SetResourceType(at auditlog.ResourceType) *AuditLogUpdate {
	alu.mutation.SetResourceType(at)
	return alu
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableResourceType(at *auditlog.ResourceType) *AuditLogUpdate {
	if at != nil {
		alu.SetResourceType(*at)
	}
	return alu
}

// ClearResourceType clears the value of the "resource_type" field.
func (alu *AuditLogUpdate) ClearResourceType() *AuditLogUpdate {
	alu.mutation.ClearResourceType()
	return alu
}

// SetIPAddress sets the "ip_address" field.
func (alu *AuditLogUpdate) SetIPAddress(s string) *AuditLogUpdate {
	alu.mutation.SetIPAddress(s)
	return alu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableIPAddress(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetIPAddress(*s)
	}
	return alu
}

// ClearIPAddress clears the value of the "ip_address" field.
func (alu *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	alu.mutation.ClearIPAddress()
	return alu
}

// SetUserAgent sets the "user_agent" field.
func (alu *AuditLogUpdate) SetUserAgent(s string) *AuditLogUpdate {
	alu.mutation.SetUserAgent(s)
	return alu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableUserAgent(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetUserAgent(*s)
	}
	return alu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (alu *AuditLogUpdate) ClearUserAgent() *AuditLogUpdate {
	alu.mutation.ClearUserAgent()
	return alu
}

// SetDetails sets the "details" field.
func (alu *AuditLogUpdate) SetDetails(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetDetails(m)
	return alu
}

// ClearDetails clears the value of the "details" field.
func (alu *AuditLogUpdate) ClearDetails() *AuditLogUpdate {
	alu.mutation.ClearDetails()
	return alu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (alu *AuditLogUpdate) AddUserIDs(ids ...uuid.UUID) *AuditLogUpdate {
	alu.mutation.AddUserIDs(ids...)
	return alu
}

// AddUser adds the "user" edges to the User entity.
func (alu *AuditLogUpdate) AddUser(u ...*User) *AuditLogUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return alu.AddUserIDs(ids...)
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (alu *AuditLogUpdate) AddTenantIDs(ids ...uuid.UUID) *AuditLogUpdate {
	alu.mutation.AddTenantIDs(ids...)
	return alu
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (alu *AuditLogUpdate) AddTenant(t ...*Tenant) *AuditLogUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return alu.AddTenantIDs(ids...)
}

// Mutation returns the AuditLogMutation object of the builder.
func (alu *AuditLogUpdate) Mutation() *AuditLogMutation {
	return alu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (alu *AuditLogUpdate) ClearUser() *AuditLogUpdate {
	alu.mutation.ClearUser()
	return alu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (alu *AuditLogUpdate) RemoveUserIDs(ids ...uuid.UUID) *AuditLogUpdate {
	alu.mutation.RemoveUserIDs(ids...)
	return alu
}

// RemoveUser removes "user" edges to User entities.
func (alu *AuditLogUpdate) RemoveUser(u ...*User) *AuditLogUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return alu.RemoveUserIDs(ids...)
}

// ClearTenant clears all "tenant" edges to the Tenant entity.
func (alu *AuditLogUpdate) ClearTenant() *AuditLogUpdate {
	alu.mutation.ClearTenant()
	return alu
}

// RemoveTenantIDs removes the "tenant" edge to Tenant entities by IDs.
func (alu *AuditLogUpdate) RemoveTenantIDs(ids ...uuid.UUID) *AuditLogUpdate {
	alu.mutation.RemoveTenantIDs(ids...)
	return alu
}

// RemoveTenant removes "tenant" edges to Tenant entities.
func (alu *AuditLogUpdate) RemoveTenant(t ...*Tenant) *AuditLogUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return alu.RemoveTenantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	alu.defaults()
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (alu *AuditLogUpdate) defaults() {
	if _, ok := alu.mutation.UpdatedAt(); !ok {
		v := auditlog.UpdateDefaultUpdatedAt()
		alu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alu *AuditLogUpdate) check() error {
	if v, ok := alu.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := alu.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	return nil
}

func (alu *AuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := alu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.UpdatedAt(); ok {
		_spec.SetField(auditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := alu.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := alu.mutation.AddedActorID(); ok {
		_spec.AddField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := alu.mutation.ActorUsername(); ok {
		_spec.SetField(auditlog.FieldActorUsername, field.TypeString, value)
	}
	if value, ok := alu.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := alu.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := alu.mutation.AddedResourceID(); ok {
		_spec.AddField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if alu.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeInt)
	}
	if value, ok := alu.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeEnum, value)
	}
	if alu.mutation.ResourceTypeCleared() {
		_spec.ClearField(auditlog.FieldResourceType, field.TypeEnum)
	}
	if value, ok := alu.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if alu.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := alu.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if alu.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := alu.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeJSON, value)
	}
	if alu.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeJSON)
	}
	if alu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.RemovedUserIDs(); len(nodes) > 0 && !alu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if alu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.RemovedTenantIDs(); len(nodes) > 0 && !alu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (aluo *AuditLogUpdateOne) SetUpdatedAt(t time.Time) *AuditLogUpdateOne {
	aluo.mutation.SetUpdatedAt(t)
	return aluo
}

// SetActorID sets the "actor_id" field.
func (aluo *AuditLogUpdateOne) SetActorID(i int) *AuditLogUpdateOne {
	aluo.mutation.ResetActorID()
	aluo.mutation.SetActorID(i)
	return aluo
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableActorID(i *int) *AuditLogUpdateOne {
	if i != nil {
		aluo.SetActorID(*i)
	}
	return aluo
}

// AddActorID adds i to the "actor_id" field.
func (aluo *AuditLogUpdateOne) AddActorID(i int) *AuditLogUpdateOne {
	aluo.mutation.AddActorID(i)
	return aluo
}

// SetActorUsername sets the "actor_username" field.
func (aluo *AuditLogUpdateOne) SetActorUsername(s string) *AuditLogUpdateOne {
	aluo.mutation.SetActorUsername(s)
	return aluo
}

// SetNillableActorUsername sets the "actor_username" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableActorUsername(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetActorUsername(*s)
	}
	return aluo
}

// SetAction sets the "action" field.
func (aluo *AuditLogUpdateOne) SetAction(s string) *AuditLogUpdateOne {
	aluo.mutation.SetAction(s)
	return aluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableAction(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetAction(*s)
	}
	return aluo
}

// SetResourceID sets the "resource_id" field.
func (aluo *AuditLogUpdateOne) SetResourceID(i int) *AuditLogUpdateOne {
	aluo.mutation.ResetResourceID()
	aluo.mutation.SetResourceID(i)
	return aluo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableResourceID(i *int) *AuditLogUpdateOne {
	if i != nil {
		aluo.SetResourceID(*i)
	}
	return aluo
}

// AddResourceID adds i to the "resource_id" field.
func (aluo *AuditLogUpdateOne) AddResourceID(i int) *AuditLogUpdateOne {
	aluo.mutation.AddResourceID(i)
	return aluo
}

// ClearResourceID clears the value of the "resource_id" field.
func (aluo *AuditLogUpdateOne) ClearResourceID() *AuditLogUpdateOne {
	aluo.mutation.ClearResourceID()
	return aluo
}

// SetResourceType sets the "resource_type" field.
func (aluo *AuditLogUpdateOne) SetResourceType(at auditlog.ResourceType) *AuditLogUpdateOne {
	aluo.mutation.SetResourceType(at)
	return aluo
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableResourceType(at *auditlog.ResourceType) *AuditLogUpdateOne {
	if at != nil {
		aluo.SetResourceType(*at)
	}
	return aluo
}

// ClearResourceType clears the value of the "resource_type" field.
func (aluo *AuditLogUpdateOne) ClearResourceType() *AuditLogUpdateOne {
	aluo.mutation.ClearResourceType()
	return aluo
}

// SetIPAddress sets the "ip_address" field.
func (aluo *AuditLogUpdateOne) SetIPAddress(s string) *AuditLogUpdateOne {
	aluo.mutation.SetIPAddress(s)
	return aluo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableIPAddress(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetIPAddress(*s)
	}
	return aluo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (aluo *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	aluo.mutation.ClearIPAddress()
	return aluo
}

// SetUserAgent sets the "user_agent" field.
func (aluo *AuditLogUpdateOne) SetUserAgent(s string) *AuditLogUpdateOne {
	aluo.mutation.SetUserAgent(s)
	return aluo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableUserAgent(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetUserAgent(*s)
	}
	return aluo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (aluo *AuditLogUpdateOne) ClearUserAgent() *AuditLogUpdateOne {
	aluo.mutation.ClearUserAgent()
	return aluo
}

// SetDetails sets the "details" field.
func (aluo *AuditLogUpdateOne) SetDetails(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetDetails(m)
	return aluo
}

// ClearDetails clears the value of the "details" field.
func (aluo *AuditLogUpdateOne) ClearDetails() *AuditLogUpdateOne {
	aluo.mutation.ClearDetails()
	return aluo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (aluo *AuditLogUpdateOne) AddUserIDs(ids ...uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.AddUserIDs(ids...)
	return aluo
}

// AddUser adds the "user" edges to the User entity.
func (aluo *AuditLogUpdateOne) AddUser(u ...*User) *AuditLogUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return aluo.AddUserIDs(ids...)
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (aluo *AuditLogUpdateOne) AddTenantIDs(ids ...uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.AddTenantIDs(ids...)
	return aluo
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (aluo *AuditLogUpdateOne) AddTenant(t ...*Tenant) *AuditLogUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return aluo.AddTenantIDs(ids...)
}

// Mutation returns the AuditLogMutation object of the builder.
func (aluo *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return aluo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (aluo *AuditLogUpdateOne) ClearUser() *AuditLogUpdateOne {
	aluo.mutation.ClearUser()
	return aluo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (aluo *AuditLogUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.RemoveUserIDs(ids...)
	return aluo
}

// RemoveUser removes "user" edges to User entities.
func (aluo *AuditLogUpdateOne) RemoveUser(u ...*User) *AuditLogUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return aluo.RemoveUserIDs(ids...)
}

// ClearTenant clears all "tenant" edges to the Tenant entity.
func (aluo *AuditLogUpdateOne) ClearTenant() *AuditLogUpdateOne {
	aluo.mutation.ClearTenant()
	return aluo
}

// RemoveTenantIDs removes the "tenant" edge to Tenant entities by IDs.
func (aluo *AuditLogUpdateOne) RemoveTenantIDs(ids ...uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.RemoveTenantIDs(ids...)
	return aluo
}

// RemoveTenant removes "tenant" edges to Tenant entities.
func (aluo *AuditLogUpdateOne) RemoveTenant(t ...*Tenant) *AuditLogUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return aluo.RemoveTenantIDs(ids...)
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (aluo *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AuditLog entity.
func (aluo *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	aluo.defaults()
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aluo *AuditLogUpdateOne) defaults() {
	if _, ok := aluo.mutation.UpdatedAt(); !ok {
		v := auditlog.UpdateDefaultUpdatedAt()
		aluo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aluo *AuditLogUpdateOne) check() error {
	if v, ok := aluo.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	return nil
}

func (aluo *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := aluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.UpdatedAt(); ok {
		_spec.SetField(auditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aluo.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := aluo.mutation.AddedActorID(); ok {
		_spec.AddField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := aluo.mutation.ActorUsername(); ok {
		_spec.SetField(auditlog.FieldActorUsername, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := aluo.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := aluo.mutation.AddedResourceID(); ok {
		_spec.AddField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if aluo.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeInt)
	}
	if value, ok := aluo.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeEnum, value)
	}
	if aluo.mutation.ResourceTypeCleared() {
		_spec.ClearField(auditlog.FieldResourceType, field.TypeEnum)
	}
	if value, ok := aluo.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if aluo.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := aluo.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if aluo.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := aluo.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeJSON, value)
	}
	if aluo.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeJSON)
	}
	if aluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.RemovedUserIDs(); len(nodes) > 0 && !aluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: auditlog.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aluo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.RemovedTenantIDs(); len(nodes) > 0 && !aluo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: auditlog.TenantPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
