// Code generated by entc, DO NOT EDIT.

package job

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCronjobid holds the string denoting the cronjobid field in the database.
	FieldCronjobid = "cronjobid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFunc holds the string denoting the func field in the database.
	FieldFunc = "func"
	// FieldCron holds the string denoting the cron field in the database.
	FieldCron = "cron"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldResourceIds holds the string denoting the resourceids field in the database.
	FieldResourceIds = "resource_ids"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the job in the database.
	Table = "jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldCronjobid,
	FieldName,
	FieldFunc,
	FieldCron,
	FieldMode,
	FieldResourceIds,
	FieldStatus,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
