// Code generated by entc, DO NOT EDIT.

package session

import (
	"time"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldConnectionId holds the string denoting the connectionid field in the database.
	FieldConnectionId = "connection_id"
	// FieldAssetId holds the string denoting the assetid field in the database.
	FieldAssetId = "asset_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldClientIP holds the string denoting the clientip field in the database.
	FieldClientIP = "client_ip"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRecording holds the string denoting the recording field in the database.
	FieldRecording = "recording"
	// FieldPrivateKey holds the string denoting the privatekey field in the database.
	FieldPrivateKey = "private_key"
	// FieldPassphrase holds the string denoting the passphrase field in the database.
	FieldPassphrase = "passphrase"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldConnectedTime holds the string denoting the connectedtime field in the database.
	FieldConnectedTime = "connected_time"
	// FieldDisconnectedTime holds the string denoting the disconnectedtime field in the database.
	FieldDisconnectedTime = "disconnected_time"

	// EdgeAssets holds the string denoting the assets edge name in mutations.
	EdgeAssets = "assets"

	// Table holds the table name of the session in the database.
	Table = "sessions"
	// AssetsTable is the table the holds the assets relation/edge.
	AssetsTable = "assets"
	// AssetsInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetsInverseTable = "assets"
	// AssetsColumn is the table column denoting the assets relation/edge.
	AssetsColumn = "session_assets"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldProtocol,
	FieldIP,
	FieldPort,
	FieldConnectionId,
	FieldAssetId,
	FieldUsername,
	FieldPassword,
	FieldCreator,
	FieldClientIP,
	FieldWidth,
	FieldHeight,
	FieldStatus,
	FieldRecording,
	FieldPrivateKey,
	FieldPassphrase,
	FieldCode,
	FieldMessage,
	FieldConnectedTime,
	FieldDisconnectedTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultConnectedTime holds the default value on creation for the "connectedTime" field.
	DefaultConnectedTime func() time.Time
	// DefaultDisconnectedTime holds the default value on creation for the "disconnectedTime" field.
	DefaultDisconnectedTime func() time.Time
	// UpdateDefaultDisconnectedTime holds the default value on update for the "disconnectedTime" field.
	UpdateDefaultDisconnectedTime func() time.Time
)
